services:
  mysql:
    image: mysql:9.5.0
    container_name: meeting-organizer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: meeting_organizer
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - meeting-organizer-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "yu71", "-p53cret" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: meeting-organizer-app
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/meeting_organizer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: yu71
#      SPRING_DATASOURCE_PASSWORD: 53cret
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - meeting-organizer-network

volumes:
  mysql-data:

networks:
  meeting-organizer-network:
    driver: bridge